### ISSUE TITLE
App crash on video upload

### ISSUE THREAD

**Issue by samsantosh** [addpipe/Pipe-Android-SDK#2]
Hey Pipe, Please check the below exception when trying to upload the video.

**As per my understanding this is happing due to the accessing the file from internal storage as Android changed the way to access the file from internal storage as per the android 'versions so to remove this exception we need to update the code for API level 23, as you didn't provide the code on git we are not able to update it as we cannot modify a .aar file**. 

```
08-04 13:02:19.219 17099-17099/test.pipe.com.pipesdktest E/AndroidRuntime: FATAL EXCEPTION: main
Process: test.pipe.com.pipesdktest, PID: 17099
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/OkHttpClient;
   at com.android.pipe.pipeandroidsdk.NetworkUtil.upload(NetworkUtil.java:42)
   at com.android.pipe.pipeandroidsdk.RecordVideoChooseActivity.upload(RecordVideoChooseActivity.java:89)
   at com.android.pipe.pipeandroidsdk.RecordVideoChooseActivity$2.onClick(RecordVideoChooseActivity.java:47)
   at android.view.View.performClick(View.java:5268)
   at android.view.View$PerformClick.run(View.java:21550)
   at android.os.Handler.handleCallback(Handler.java:822)
   at android.os.Handler.dispatchMessage(Handler.java:104)
   at android.os.Looper.loop(Looper.java:207)
   at android.app.ActivityThread.main(ActivityThread.java:5811)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.OkHttpClient" on path: DexPathList[[zip file "/data/app/test.pipe.com.pipesdktest-1/base.apk"],nativeLibraryDirectories=[/data/app/test.pipe.com.pipesdktest-1/lib/arm, /vendor/lib, /system/lib]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
   at com.android.pipe.pipeandroidsdk.NetworkUtil.upload(NetworkUtil.java:42) 
   at com.android.pipe.pipeandroidsdk.RecordVideoChooseActivity.upload(RecordVideoChooseActivity.java:89) 
   at com.android.pipe.pipeandroidsdk.RecordVideoChooseActivity$2.onClick(RecordVideoChooseActivity.java:47) 
   at android.view.View.performClick(View.java:5268) 
   at android.view.View$PerformClick.run(View.java:21550) 
   at android.os.Handler.handleCallback(Handler.java:822) 
   at android.os.Handler.dispatchMessage(Handler.java:104) 
   at android.os.Looper.loop(Looper.java:207) 
   at android.app.ActivityThread.main(ActivityThread.java:5811) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681) 
	Suppressed: java.lang.ClassNotFoundException: com.squareup.okhttp.OkHttpClient
   at java.lang.Class.classForName(Native Method)
   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
   		... 13 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by pabloruan0710** [comment]
@samsantosh Your project is working? What your make for fixed this problem?

**Comment by remusnegrota** [comment]
We've stopped maintaining our native iOS and Android SDKs in favor of a POST API which can be used by:
    any server-side app
    any mobile app regardless of the platform (Objective C, Java, HTML &JS, etc.)

Email us at hello@addpipe.com for further details.
